### ISSUE TITLE
Free/Open Licenses Data Package

### ISSUE THREAD

**Issue by Ebnalblad** [okfn/licenses#44] opened 2015-04-18 20:58 UTC
I have been following the issues about Core Datasets as Data Packages project (http://data.okfn.org/roadmap/core-datasets) and I suggested to make data package for Free/Open Licenses https://github.com/datasets/registry/issues/85
@rgrp told me that you had already worked on Free/Open Licenses data, so what do you think about my suggestion ?

**Comment by rgrp** [comment] 2015-04-18 21:54
I'm involved here btw - but others are too.

Here's my immediate thoughts:

- Yes, let's convert this to a simple tabular data package
- People depend on our data (this site gets deployed at http://licenses.opendefinition.org/) and has a bunch of json. We need not to break that for folks. I suggest we think properly about what API we want to offer and plan that out.
- Separately, but relatedly, we want to work out whether we want to break out the online / API stuff and move to main opendefinition repo https://github.com/okfn/opendefinition/issues/7

**Comment by rgrp** [comment] 2015-04-18 22:05
@Ebnalblad for context see #45

**Comment by Ebnalblad** [comment] 2015-04-18 22:31
I am not sure I understand every thing you said, I do not have very good technical knowledge.
I think we agreed  to make simple tabular data package. Let me explain my idea more I am thinking of  dataset contains tables, such as, the name of license, the link for it, can be use for commercial purposes, the last version of license and so on. By this way it would be easy for people who wants to use these licenses to get all information they want about them from single dataset.
I am open to other suggestion if I have the ability to do it .

**Comment by mlinksva** [comment] 2015-04-19 04:33
Skimming http://data.okfn.org/doc/data-package it seems like the obvious thing to do is to add a datapackage.json file to this repository.

I'm not sure what is to be gained by converting the existing json data to tabular data, but if there's a use case of course go for it. Preferably generating one way so the data isn't maintained in yet another place.

Thanks!

**Comment by rgrp** [comment] 2015-04-19 08:40
@mlinksva understood. Perhaps more importantly what do you think of #45? That really sets out a bit more clearly what is going on.

To be clear i think we will have both csv and json but standard form with be CSV. Why CSV? Simpler, anyone can open, and it makes valid tabular data packages :-)

**Comment by rgrp** [comment] 2015-04-19 09:18
@Ebnalblad ok, here's what i suggest are your next steps:

- convert the list of all licenses (all.json) to csv - https://github.com/okfn/licenses/blob/master/licenses/groups/all.json - i hope it is obvious how to do this (if not just ask). I would put the csv file at the base of the repo. Make sure we do this in the master branch (i've now made default branch for repo the master branch)
- add a datapackage.json so this is a proper data package

These are all "enhancments" that take nothing away, plus in master branch so we won't affect the website (http://licenses.opendefinition.org/) which deploys off the github pages branch.

**Comment by Ebnalblad** [comment] 2015-04-20 15:29
I searched online about how to convert  json to csv and i tried my services to convert  all.json file to csv file but it seems there are some mistakes in .json file
 " Make sure we do this in the master branch (i've now made default branch for repo the master branch)"
You mean here https://github.com/okfn/licenses ?

**Comment by rgrp** [comment] 2015-04-20 15:31
You really want to script that if you can. Very easy in a bit of code.

Maybe @jonschlinkert can help here

**Comment by Ebnalblad** [comment] 2015-04-20 15:41
unfortunately I do not know. if there are some instructions on the web from scratch,  maybe then I could do it.

**Comment by jonschlinkert** [comment] 2015-04-20 16:50
> Maybe @jonschlinkert can help here

meaning converting from csv to json?

**Comment by rgrp** [comment] 2015-04-20 18:23
other way: json to csv

**Comment by jonschlinkert** [comment] 2015-04-20 22:59
got it, thanks. I'll take a look. is this something that should be done before the other tasks, or alongside the other tasks? 

@Ebnalblad what kinds of conversion issues were you getting? was it formatting-related (e.g. data structure) or were there errors in the actual content itself? (for example, nested/escaped quotes sometimes cause issues)

**Comment by Ebnalblad** [comment] 2015-04-21 05:11
@jonschlinkert when i tried to convert the it i was getting errors messages that there are errors in some content lines .

**Comment by rgrp** [comment] 2015-04-26 18:20
@jonschlinkert @Ebnalblad this should be super straight forward. We just want to turn https://github.com/okfn/licenses/blob/master/licenses/groups/all.json into a CSV and put it in a `/data/` directory. (After that we create the data package).

**Comment by rgrp** [comment] 2015-05-03 11:51
@jonschlinkert and @Ebnalblad any updates here? Should be very straightforward to do and once done we can move on to #45

**Comment by Ebnalblad** [comment] 2015-05-04 20:34
@rgrp sorry for late i asked my friend to help me, is it ok now

**Comment by jonschlinkert** [comment] 2015-05-22 21:55
sorry for the lack of response, had some deadline driven projects. I see there is a CSV in the repo, looks like that part is taken care of, what's next? something I can help with?

**Comment by rgrp** [comment] 2015-05-26 12:39
@jonschlinkert the csv'ing and data packaging is done thanks to @Ebnalblad - back now to #45

**Comment by rgrp** [comment] 2015-05-26 12:39
FIXED - thanks to @Ebnalblad

**Comment by mlinksva** [comment] 2015-06-16 17:33
Is the CSV file now the one place to make changes? If it is pull requests #52 and #53 should be rewritten to update the CSV instead of individual license json files. Not clear to me what the state of this is, so asking folks who participated in the CSV'ing.

**Comment by rgrp** [comment] 2015-06-19 02:18
@mlinksva good question - the basic answer should be "yes" - the issue is that is #45 is still incomplete and we need to complete that before that is truly the situation. Will seek to push forward with #45 asap. In the mean time I guess we can merge those pull requests though we should also patch the CSV file at the same time (this duping will go away with #45)

**Comment by rgrp** [comment] 2015-11-30 19:59
FIXED. Closing again as i think we are all done here.

**Closed by rgrp** 2015-11-30 19:59 UTC
